### PR TITLE
fix: make dynamic dispatch delegate to inner AIR logic

### LINKED ISSUE #220: bug: dynamic dispatch skips actual table constraint evaluation
Mentioned by @hratoanina 

Running any poseidon example with invalid AIR constraints for poseidon2 table (or even a `panic!()` inside) will pass fine. Seems to be caused by dynamic dispatch logic

### PR DESCRIPTION
**Pull request by Nashtare**
# Description

We were not delegating to the actual inner AIRs when performing dynamic dispatch of non-primitive operations, which would make anything pass without any actual checks.

# Changes

I've implemented `eval` for `Poseidon2AirWrapper`. It was messy because of type inferences and Rust limitations so unlike primitive tables, the `eval` implementation had to be duplicated: one for `SymbolicAirBuilder`, one for `ProverConstraintFolder`, etc...
I tried wrapping most of redundancies together to reduce duplication.

closes #220

### CODE REVIEW

File: circuit-prover/src/batch_stark_prover.rs [hunk 1]
```diff
@@ -871,6 +1598,7 @@ where
                 use p3_poseidon2_circuit_air::Poseidon2CircuitAirBabyBearD4Width16;
                 let air = Poseidon2CircuitAirBabyBearD4Width16::new(constants.clone());
```
Comment (sai-deng) [inline circuit-prover/src/batch_stark_prover.rs]: This creates an AIR for width(), then creates a different AIR via to_air_wrapper(). Could we use the same instance to avoid potential state inconsistency?

File: circuit-prover/src/batch_stark_prover.rs [hunk 2]
```diff
@@ -476,37 +513,722 @@ where
...
+impl<SC> AirLookupHandler<SymbolicAirBuilder<Val<SC>>> for Poseidon2AirWrapper<SC>
+where
+    SC: StarkGenericConfig + Send + Sync,
+    Val<SC>: StarkField + PrimeField,
+{
+    fn add_lookup_columns(&mut self) -> Vec<usize> {
+        match &mut self.inner {
+            Poseidon2AirWrapperInner::BabyBearD4Width16(air) => unsafe {
+                let air_bb: &mut Poseidon2CircuitAirBabyBearD4Width16 =
+                    core::mem::transmute(air.as_mut());
```
Comment (sai-deng) [inline circuit-prover/src/batch_stark_prover.rs]: Is this transmute needed? air.as_mut() already returns the correct type.

File: circuit-prover/src/batch_stark_prover.rs [hunk 3]
```diff
@@ -476,37 +513,722 @@ where
...
+
+    #[allow(clippy::missing_transmute_annotations)] // this gets overly verbose otherwise
+    fn get_lookups(&mut self) -> Vec<p3_lookup::lookup_traits::Lookup<Val<SC>>> {
+        match &mut self.inner {
+            Poseidon2AirWrapperInner::BabyBearD4Width16(air) => unsafe {
+                let air_bb: &mut Poseidon2CircuitAirBabyBearD4Width16 =
+                    core::mem::transmute(air.as_mut());
+                let lookups_bb = <Poseidon2CircuitAirBabyBearD4Width16 as AirLookupHandler<
+                    SymbolicAirBuilder<BabyBear>,
+                >>::get_lookups(air_bb);
```
Comment (sai-deng) [inline circuit-prover/src/batch_stark_prover.rs]: Should we add a runtime guard ensure Val<SC> matches the field type?

File: poseidon2-circuit-air/src/air.rs [hunk 4]
```diff
@@ -434,7 +437,7 @@ pub fn extract_preprocessed_from_operations<F: Field, OF: Field>(
     preprocessed
 }
 
-fn eval<
+pub fn eval<
```
Comment (sai-deng) [inline poseidon2-circuit-air/src/air.rs]: Is pub fn eval intentionally public API? If only eval_unchecked needs external visibility, could this be pub(crate)?

**Review by sai-deng — APPROVED** [review]
